### Server configuration ###
server:
  port: 8082
  shutdown: graceful
  netty:
    connection-timeout: 2s
    idle-timeout: 15s

spring:
  application:
    name: payment-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: "http://localhost:9001"
      request-connect-timeout: 5000
      request-read-timeout: 5000
      fail-fast: false
      retry:
        max-attempts: 5
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
    function:
      definition: userPaymentNotified
    stream:
      bindings:
        userPaymentNotified-in-0: # userPaymentNotified function will be bound to the notification-success destination
          destination: notification-success
          group: ${spring.application.name} # consumer group
        paymentAccepted-out-0: # BridgeStream will bind it to the notify-user destination, see PaymentService.makePayment()
          destination: notify-user
      defaultBinder: rabbit
      
rabbitmq:
  host: localhost
  port: 5672
  username: rabbit
  password: rabbit
  connection-timeout: 5s

# Enable refresh endpoint of the actuator, exposes HTTP /actuator/refresh endpoint
management:
  endpoints:
    web.exposure.include: refresh

config:
  invoice-service-uri: "http://localhost:8081"
