logging:
  level:
    org.springframework: debug

#############Persistence #####################
spring:
  r2dbc:
    driver-class-name: org.h2.Driver
    url: r2dbc:h2:file:///~/paymentService
    username: sa
    password: sa
    pool:
      max-create-connection-time: 2s
      initial-size: 1
      max-size: 1

#  sql:
#   init:
#     mode: always

  flyway:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/paymentService
    user: sa
    password: sa


