spring:
  r2dbc:
    driver-class-name: org.postgresql.Driver
    url: r2dbc:postgresql://localhost:5432/invoiceService
    username: postgres
    password: postgres
    pool:
      max-create-connection-time: 2s
      initial-size: 5
      max-size: 10

flyway:
  url: jdbc:postgresql://localhost:5432/invoiceService
  username: ${spring.r2dbc.username}
  password: ${spring.r2dbc.password}