name: commit stage
on: push
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: microservicesexample/payment-service
  VERSION: latest

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      security-events: write
    
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: maven
      - name: Code vulnarabilty scanning
        uses: anchore/scan-action@v3
        id: scan
        with: 
          path: "${{ github.workspace }}"
          fail-build: false
          severity-cutoff: high
          
      - name: Upload vulnarabilty report
        uses: github/codeql-action/upload-sarif@v2
        if: success() || failure()
        with:
          sarif_file:  ${{ steps.scan.outputs.sarif }}
      - name: Build, Unit and Integration tests
        run: |
            chmod +x mvnw
            ./mvnw install -Dspring.profiles.active=testdata
      - name: Validate K8S manifests
        uses: stefanprodan/kube-tools@v1
        with:
          kubectl: 1.24.3
          kubeval: 0.16.1
          command: |
                  kubeval --strict -d k8s
  
  package:
    name: Package and Publish Image
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [ build ]
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
      security-events: write
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: maven
      - name: Build container image
        run: |
            chmod +x mvnw
            ./mvnw spring-boot:build-image \
            -Dimage.name=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
      - name: Container image vulnerabilty scanning
        uses: anchore/scan-action@v3
        id: scan
        with:
          image:
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          fail-build: false
          severity-cutoff: high
      - name: Upload vulnarabilty report
        uses: github/codeql-action/upload-sarif@v2
        if: success() || failure()
        with:
          sarif_file:  ${{ steps.scan.outputs.sarif }}
      - name: Login to container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish container image
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
